name: Report PR Age

on:
    pull_request:

jobs:
    report-pr-age:
        name: Report stuff about PR
        runs-on: ubuntu-20.04
        steps:
        - name: get PR age
          run: |
            pr_age=$((($(date '+%s') - $(date -d "${{ github.event.pull_request.created_at }}" '+%s'))))
            echo pr_age=$pr_age >> $GITHUB_ENV
            first_commit_mesage=$(curl -s "${{github.event.pull_request._links.commits.href}}" | jq '.[0].commit.message')
            echo first_commit_mesage=$first_commit_mesage >> $GITHUB_ENV
            if echo "${{github.event.pull_request.title}}" | grep -Eiq "^reverts?"; then
                echo is_revert=true >> $GITHUB_ENV
            else
                echo is_revert=false >> $GITHUB_ENV
            fi
        - name: debug out
          uses: hmarr/debug-action@v2
        - name: capture PR age to PostHog
          uses: PostHog/posthog-github-action@v0.1
          with:
            posthog-token: ${{secrets.POSTHOG_API_TOKEN}}
            event: 'posthog-ci-pr-age-when-closed'
            properties: '{"prAgeInSeconds": ${{ env.pr_age }}, "isRevert": ${{env.is_revert}} }'
