name: Report PR Age

on:
    pull_request:

jobs:
    report-pr-age:
        name: Report stuff about PR
        runs-on: ubuntu-20.04
        steps:
        - name: get PR age
          run: |
            echo github.event | python -m json.tool
            pr_age=$((($(date '+%s') - $(date -d "${{ github.event.pull_request.created_at }}" '+%s'))))
            echo pr_age=$pr_age >> $GITHUB_ENV
        - name: capture PR age to PostHog
          uses: PostHog/posthog-github-action@v0.1
          with:
            posthog-token: ${{secrets.POSTHOG_API_TOKEN}}
            event: 'posthog-ci-pr-age-when-closed'
            properties: '{"prAgeInSeconds": ${{ env.pr_age }}}'
